[2013-01-28 00:00:30,090][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-28 00:04:30,453][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-28 00:08:30,762][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-28 00:10:50,381][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xfe3d8096]], closing connection
java.net.SocketException: Network is down
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:652)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-28 00:10:50,383][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xbe1db270]], closing connection
java.net.SocketException: Network is down
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:652)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-28 00:10:50,386][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x649a546c]], closing connection
java.net.SocketException: Network is down
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-28 00:10:50,391][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xa43eab64]], closing connection
java.net.SocketException: Network is down
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-28 00:10:50,393][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x29bc6bcf]], closing connection
java.net.SocketException: Network is down
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-28 00:10:50,395][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x98f2411b]], closing connection
java.net.SocketException: Network is down
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-28 00:10:50,403][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x74657621]], closing connection
java.net.SocketException: Network is down
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-28 00:10:50,406][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0xb85ea6c3]], closing connection
java.net.SocketException: Network is down
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:655)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-28 00:10:50,409][WARN ][transport.netty          ] [Agony] exception caught on transport layer [[id: 0x14296839]], closing connection
java.net.SocketException: Network is down
	at sun.nio.ch.Net.connect(Native Method)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:532)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:148)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:568)
	at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:642)
	at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:658)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
[2013-01-28 11:45:16,791][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-28 11:49:17,090][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-28 11:53:17,388][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-28 11:57:52,281][WARN ][cluster.service          ] [Agony] failed to reconnect to node [Agony][mzwJxYAgQNC_ICDJWLgu3g][inet[/192.168.2.13:9300]]
org.elasticsearch.transport.ConnectTransportException: [Agony][inet[/192.168.2.13:9300]] connect_timeout[30s]
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:665)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:604)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:574)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
	at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:395)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.net.ConnectException: connection timed out
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processConnectTimeout(NioClientSocketPipelineSink.java:484)
	at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:369)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
[2013-01-28 14:36:33,147][INFO ][node                     ] [Agony] {0.20.1}[10874]: stopping ...
[2013-01-28 14:36:33,912][INFO ][node                     ] [Agony] {0.20.1}[10874]: stopped
[2013-01-28 14:36:33,912][INFO ][node                     ] [Agony] {0.20.1}[10874]: closing ...
[2013-01-28 14:36:34,051][INFO ][node                     ] [Agony] {0.20.1}[10874]: closed
